- hosts: localhost
  connection: local
  gather_facts: yes
  become: false
  vars:
    ls: ls
    directories:
      - ~/.sh
      - ~/.sh/plugins
      - ~/.vim
      - ~/.vim/rc
    common_packages:
      - git
      - vim
      - zsh
      - tmux
      - curl
      - tree
      - nkf
      - coreutils
    dotfiles:
      - bashrc
      - zshrc
      - sh/alias.sh
      - sh/common.sh
      - sh/common.zsh
      - sh/fzf.sh
      - vimrc
      - vim/rc/neobundle.vim
      - gitconfig
      - gemrc
      - tmux.conf
    repositories:
      - junegunn/fzf
      - seebi/dircolors-solarized
      - rupa/z
      - Shougo/neobundle.vim
      - sstephenson/rbenv
      - sstephenson/ruby-build
      - creationix/nvm
  tasks:
    - include_vars: main.yml
    - include_vars: "{{ansible_os_family}}.yml"

    - name: be sure apt repository is updated
      apt: update_cache=yes
      become: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: be sure common packages are installed
      package: name={{item}} state=latest
      become: "{{package_user}}"
      with_items: common_packages

    - name: be sure packages for os are installed
      package: name={{item}} state=latest
      become: "{{package_user}}"
      with_items: packages_for_os

    - name: be sure necessary directory exists
      file: path={{item}} state=directory
      with_items: directories

    - name: be sure dotfiles are installed
      template: "src=templates/{{item}}.j2 dest=~/.{{item}}"
      with_items: dotfiles

    # setup shell
    - stat: path=~/bin/ghq
      register: ghq

    - name: be sure ghq is installed
      shell: GOPATH=~/ go get github.com/motemen/ghq
      when: not ghq.stat.exists

    - name: be sure github repositories is downloaded
      shell: ~/bin/ghq get {{item}} -u
      with_items: repositories

    - name: be sure symlink exists at ~/.fzf
      file: src=~/src/github.com/junegunn/fzf dest=~/.fzf state=link

    - name: be sure fzf is installed
      shell: ~/.fzf/install

    - name: be sure z is isntalled
      file: src=~/src/github.com/rupa/z/z.sh dest=~/.sh/plugins/z.sh state=link

    - name: be sure .dircolors exists
      file: src=~/src/github.com/seebi/dircolors-solarized/dircolors.ansi-universal dest=~/.dircolors state=link

    # setup vim
    - stat: path=~/.vim/bundle/neobundle.vim
      register: neobundle

    - name: be sure neobundle is installed
      shell: ~/src/github.com/Shougo/neobundle.vim/bin/install.sh
      when: not neobundle.stat.exists

    - name: be sure neobundle plugins are installed
      shell: ~/src/github.com/Shougo/neobundle.vim/bin/neoinstall
      when: not neobundle.stat.exists

    # setup rbenv
    - name: be sure symlink exists at ~/.rbenv
      file: src=~/src/github.com/sstephenson/rbenv dest=~/.rbenv state=link

    - name: be sure plugins directory at ~/.rbenv
      file: path=~/.rbenv/plugins state=directory

    - name: be sure symlink exists at ~/.rbenv/plugins/ruby-build
      file: src=~/src/github.com/sstephenson/ruby-build dest=~/.rbenv/plugins/ruby-build state=link

    - name: has ruby already been installed?
      shell: "rbenv versions | grep -q {{ ruby_version }}"
      register: ruby_installed
      failed_when: ruby_installed.rc not in [0, 1]

    - name: be sure ruby is installed
      shell: "CONFIGURE_OPtS='--disable-install-rdoc' rbenv install {{ ruby_version }}"
      when: ruby_installed|failed

    - name: be sure ruby version has been set
      shell: "rbenv global {{ ruby_version }}"

    - name: be sure gem-src is installed
      shell: "~/.rbenv/shims/gem install gem-src"

    - name: be sure bundler is installed
      shell: "~/.rbenv/shims/gem install bundler"

    # setup nvm
    - git: repo=https://github.com/creationix/nvm.git dest=~/.nvm

    - name: be sure node is installed
      shell: ". ~/.nvm/nvm.sh && nvm install {{ node_version }}"

    - name: be sure default node version is set
      shell: ". ~/.nvm/nvm.sh && nvm alias default {{ node_version }}"
